version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: pos-master-db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: master_db
    ports:
      - "5432:5432"
    restart: always

  redis:
    image: redis:alpine
    container_name: redis-cache
    ports:
      - "6379:6379"
    restart: always